Hw2
karmanovalexey/2019-2-Track-Frontend-A-Karmanov pull request #2
Opened 2019-10-14 20:55 UTC by karmanovalexey

# Домашнее задание №

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Окно чата стилизовано под образец
* 
*

2019-10-15 15:59 UTC, priver requested changes

2019-10-15 15:59 UTC, priver commented on web-components/src/components/MessageForm.js
> +    this.addMessage(this.messageObj);
зачем сначала записывать в this, а потом передавать в качестве аргумента?

2019-10-15 15:59 UTC, priver commented on web-components/src/components/MessageForm.js
> +    const divFormatMessageContainer = document.createElement('div');
нужно создать отдельный компонент для сообщения

2019-10-20 18:07 UTC, karmanovalexey commented
https://karmanovalexey.github.io/2019-2-Track-Frontend-A-Karmanov/

2019-10-21 10:09 UTC, priver approved these changes
Отлично, 10 баллов (-2 за сдачу не в срок)

2019-10-21 10:09 UTC, merged