Hw5
karmanovalexey/2019-2-Track-Frontend-A-Karmanov pull request #5
Opened 2019-12-05 10:45 UTC by karmanovalexey

# Домашнее задание № 5

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* компоненты переписаны под реакт
* Трэвис просил обновить package-lock, после обновления и произведения коммита было добавлено огромное количество строк
*

2019-12-06 04:43 UTC, martinkomitsky commented on package.json
> +	"homepage": "https://your_gh_login.github.io/your_repo_name",
"https://karmanovalexey.github.io/2019-2-Track-Frontend-A-Karmanov/", ????

2019-12-06 04:43 UTC, martinkomitsky requested changes
Проверка, что домашнее задание раздеплоено и корректно работает не выполнена. Проверять ДЗ не могу.

2019-12-06 07:13 UTC, karmanovalexey commented
Виноват, просто забыл про gh_pages, вроде исправил

2019-12-06 08:52 UTC, karmanovalexey commented
Поправочка, при деплое рефы ломаются, хотя локально все норм, не знаю, что делать
![Screenshot from 2019-12-06 11-48-31](https://user-images.githubusercontent.com/55716298/70309586-e4818380-181e-11ea-9f4b-3b1ddda67fc9.png)

2019-12-09 07:13 UTC, martinkomitsky requested changes
Исправить:

1. Можно отправлять пустые сообщения
2. Не отправляются сообщения по "enter"
3. При отправке сообщений нет анимации из 4 ДЗ

2019-12-10 04:22 UTC, martinkomitsky requested changes
Теперь все очень хорошо, правда, нет доскролла из какого-то еще более древнего ДЗ. 

Нужно доделать последнюю правку: 
* При отправке сообщений в чат нужно делать скролл до последнего элемента (иначе, если много сообщений, то новые сообщения не видны)

2019-12-11 04:05 UTC, martinkomitsky approved these changes
10

2019-12-11 04:05 UTC, merged